name: PR Description Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check PR description for :yellow-man:
        run: |
          # Obtem a descrição da PR
          pr_description=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          
          # Verifica se a descrição contém a palavra proibida
          if echo "$pr_description" | grep -q ":yellow-man:"; then
            echo "Found ':yellow-man:' in the PR description. Failing the job."
            exit 1
          else
            echo "PR description is valid."
          fi
