name: Canary Test - Guidelines

on:
  pull_request:
    types: [opened, synchronize, reopened, draft]

jobs:
  keyword_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Description for Keyword
        run: |
          # Get the PR description using GitHub REST API
          pr_body=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            | jq -r .body)
          
          # Check if the keyword ":yellow-man:" is present in the PR description
          if echo "$pr_body" | grep -F ":yellow-man:"; then
            echo "Please, read our guidelines before opening a PR."
            exit 1
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
