name: Check for :yellow-man: in PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check for :yellow-man: in PR body
        uses: actions/github-script@v6
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (prBody && prBody.includes(':yellow-man:')) {
              core.setFailed('PR contains :yellow-man:');
            } else {
              console.log('No :yellow-man: found in PR description.');
            }
