name: Canary Test - Guidelines

on:
  pull_request:
    types: [opened, synchronize, reopened, draft]

jobs:
  keyword_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Description for Keyword
        run: |
          pr_body=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
          if echo "$pr_body" | grep -F ":yellow-man:"; then
            echo "Please, read our guidelines before opening a PR."
            exit 1
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
