name: PR Description Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Debug - Print PR description
        run: |
          # Obtem a descrição da PR
          pr_description=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          
          # Imprime a descrição da PR para depuração
          echo "PR Description: $pr_description"

      - name: Check PR description for yellow-man
        run: |
          # Obtem a descrição da PR
          pr_description=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          
          # Verifica se a descrição contém a palavra proibida, ignorando diferenças de espaços ou quebras de linha
          if echo "$pr_description" | grep -iq "yellow-man"; then
            echo "This is a canary test for our guidelines. Please, read our guidelines before proceeding with your PR."
            exit 1
          else
            echo "Thanks for reading our guidelines."
          fi
